---
stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: Build
        displayName: Build the Function App
        pool:
          vmImage: windows-latest
        steps:
          - checkout: self
            submodules: true
            persistCredentials: true
          - task: UseDotNet@2
            inputs:
              packageType: sdk
              version: 5.x
              installationPath: $(Agent.ToolsDirectory)/dotnet
          - script: |
              echo  '$(System.DefaultWorkingDirectory)'
              cd src/MyFunctionApp.Functions
              dotnet restore
              dotnet build --configuration Release
            displayName: Build the Azure

  - stage: Test
    displayName: Test Stage
    dependsOn: Build
    jobs:
      - job: Test
        displayName: Run Unit Tests
        pool:
          vmImage: windows-latest

  - stage: Deploy
    displayName: Deploy to Azure
    dependsOn: Test
    jobs:
      - job: Deploy
        displayName: Deploy Function to Azure
        pool:
          vmImage: windows-latest
