---
stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: Build
        displayName: Build the Function App
        pool:
          vmImage: windows-latest
        steps:
          - checkout: self
            submodules: true
            persistCredentials: true
          - task: UseDotNet@2
            inputs:
              packageType: sdk
              version: 5.x
              installationPath: $(Agent.ToolsDirectory)/dotnet
          - script: |
              echo  '$(System.DefaultWorkingDirectory)'
              dir
              dotnet restore
              dotnet build --configuration Release
            displayName: Build the Azure