#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/azure-functions/dotnet:3.0 AS base
WORKDIR /home/site/wwwroot
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY . .

# use the label to identity this layer later
LABEL test=true
# run the test and collect code coverage (requires coverlet.msbuild to be added to test project)
RUN dotnet test LineTen.Callback.sln  --collect:"XPlat Code Coverage" --results-directory /testresults --logger trx ; exit 0
# install the report generator tool
RUN dotnet tool install dotnet-reportgenerator-globaltool --version 4.5.2 --tool-path /tools
# generate final coverlet file reports using report generator tool (merge togoether)
RUN /tools/reportgenerator "-reports:/testresults/**/coverage.cobertura.xml" "-targetdir:/testresults/coverage" "-reportTypes:Cobertura"

WORKDIR "/src/MyFunctionApp.Functions"
RUN dotnet build "MyFunctionApp.Functions.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MyFunctionApp.Functions.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /home/site/wwwroot
COPY --from=publish /app/publish .
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true